### ISSUE TITLE
Console error: 'class' used instead of 'className' in Navbar.js and AllCategories.js

### ISSUE THREAD

**Issue by haingo-raz** [Kanika637/amazon-clone#105]
![console error](https://user-images.githubusercontent.com/100688816/195087169-36a981a9-4d1d-415d-aa95-36b50406bcd9.png)

**Comment by Kanika637** [comment]
Thanks for opening the issue! Go ahead @haingo-raz 🚀

**Comment by RutamBhagat** [comment]
@Kanika637 can you please assign this issue to me
I am new to hacktoberfest
