### ISSUE TITLE
Improve the header

### ISSUE THREAD

**Issue by Aakash441** [Kanika637/amazon-clone#106]
### Is your feature request related to a problem? Please describe.

The text in the header and its placement does not look. Also there is hello written above select your location which is not needed.

### Describe the solution you'd like

Remove the hello text placed above select the location. Improve the text positioning and text font basically making changes in css.

**Comment by Kanika637** [comment]
Thanks for opening the issue! go ahead @Aakash441 🚀
I would suggest you take care of the CSS as we have recently merged a PR handling the responsiveness of the header.
