### ISSUE TITLE
One product's information is missing

### ISSUE THREAD

**Issue by Kanika637** [Kanika637/amazon-clone#108]
### Describe the bug

**Current Behaviour**

![image](https://user-images.githubusercontent.com/84350895/195146451-aa5f4686-0a39-4f9b-a10b-9cdae06ec7aa.png)

As we can see that the product's info is missing.

### Expected behaviour

We want you to change that product with full information. You can add any product eg: a Bluetooth speaker.

**Comment by Devesh-coder** [comment]
I would like to contribute to this issue

**Comment by zugzwang03** [comment]
why is this issue termed as invalid? @Kanika637

**Comment by Jai-Solania-29** [comment]
Hey @zugzwang03 thanks for letting us know, it's was a mistake we have corrected it.
Do you want to work on the issue?

**Comment by zugzwang03** [comment]
yep

**Comment by zugzwang03** [comment]
I can work on it

**Comment by Jai-Solania-29** [comment]
Ok go ahead 🚀
Assigning you the issue ✅
