### ISSUE TITLE
Alignment of "Shop by Category" section is incorrect

### ISSUE THREAD

**Issue by Kanika637** [Kanika637/amazon-clone#109]
### Describe the bug

**Current Behaviour**

![image](https://user-images.githubusercontent.com/84350895/195147388-248b025d-2661-4dc1-a8db-f12e94d89841.png)

As you can see the alignment between the three sections is not appropriate.

![image](https://user-images.githubusercontent.com/84350895/195147890-65ef0d69-0088-466d-8def-6a40e44de759.png)

Also the "Shop now" button is not correctly aligned, it should be centre aligned.

### Expected behaviour

The spacing between all those three sections should be equal.

**Comment by priyanshusingh305** [comment]
Hi @Kanika637,
assign me, please

**Comment by Devesh-coder** [comment]
Hey @Kanika637 would like to contribute to it!

**Comment by Kanika637** [comment]
As per first come first serve @priyanshusingh305, Assigning you the issue!

**Comment by Kanika637** [comment]
@Devesh-coder, We have more issues, you can work on them!🚀

**Comment by priyanshusingh305** [comment]
@Kanika637 
![Uploading image.png…]()
are these alignments are good?
pr request #116
