### ISSUE TITLE
Some problems in the Shopping Basket page

### ISSUE THREAD

**Issue by Kanika637** [Kanika637/amazon-clone#110]
### Is your feature request related to a problem? Please describe.

**Current Behaviour**

![image](https://user-images.githubusercontent.com/84350895/195148358-b0b98fbd-2d42-45d8-aab4-b37530c1c7ca.png)

-> The "Remove Form basket" button does not look appropriate.

![image](https://user-images.githubusercontent.com/84350895/195148846-82196a11-9fd4-43ae-9fe8-aba095e8d0b3.png)

-> As we can see the "Subtotal" box does not look appropriate.

### Describe the solution you'd like

**Expected Behaviour**

-> We want the button to look like this👇

![image](https://user-images.githubusercontent.com/84350895/195148652-0c743351-e835-4864-9d04-c668d8a6832f.png)

-> We want the "Subtotal" box to look like this👇
Try to achieve maximum similarity

![image](https://user-images.githubusercontent.com/84350895/195149558-01bb56cc-2005-4f7d-862b-783d0f1b1e30.png)

You can ignore the green text above.

**Comment by jsvigneshkanna** [comment]
Please assign me this issue, will work on it

**Comment by Kanika637** [comment]
Great! Go ahead @jsvigneshkanna 🚀
Just make sure to provide all the screenshots of your work, while making Pr, as this issue contains a lot of content.
