### ISSUE TITLE
Make Products on homepage dynamic and improve CSS

### ISSUE THREAD

**Issue by ShubhamPatil0723** [Kanika637/amazon-clone#113]
### Is your feature request related to a problem? Please describe.

Currently, product props are passed manually making this website static.

### Describe the solution you'd like

 We can create an array with product details and generate products according to the array making it dynamic.

**Comment by ShubhamPatil0723** [comment]
Please assign this issue to me

**Comment by priyanshusingh305** [comment]
I think you should use ![faker api](https://www.npmjs.com/package/faker)
for dynamic product json
Best of luck!

**Comment by Kanika637** [comment]
Thanks for opening the issue @ShubhamPatil0723 , Go ahead🚀

**Comment by Kanika637** [comment]
Any updates @ShubhamPatil0723 ?

**Comment by ShubhamPatil0723** [comment]
@priyanshusingh305 yeah that would work but it gives random products, in future we will get products from our own database that's why I'm fetching data from array :eyes:

**Comment by ShubhamPatil0723** [comment]
> Any updates @ShubhamPatil0723 ?

Yeah, I have fixed the redundant code and it's responsive but that carousal is problem so I'll be working on it on this Saturday
