### ISSUE TITLE
[DOCS] A separate file can be created for "Steps to open a new issue" 

### ISSUE THREAD

**Issue by Vanshiii203** [Kanika637/amazon-clone#122]
### Description

A separate file can be created for "Steps to open a new issue" and the link of that file can be added to the readme to make the readme look more systematic.

**Comment by Kanika637** [comment]
Thanks for opening the issue @Vanshiii203 since we have changed the template for opening new issues, I think it is mandatory to change it in the readme.md as well. Go ahead🚀

**Comment by Kanika637** [comment]
Any updates @Vanshiii203 ?

**Comment by Vanshiii203** [comment]
> Any updates @Vanshiii203 ?

I'll raise a pr by tomorrow
