### ISSUE TITLE
Sign in form can't take mobile numbers as login username

### ISSUE THREAD

**Issue by mecskyverse** [Kanika637/amazon-clone#123]
### Describe the bug

In Login Form while creating a new account there is a option of entering either Mobile Number or email

![image](https://user-images.githubusercontent.com/91150257/196037368-024e6bc6-f71b-4733-8fe1-0f5a76c462f3.png)

But we can't enter the mobile number as a login credential because it only accepts email id as a credential
![image](https://user-images.githubusercontent.com/91150257/196037571-f3749d9a-5991-45f2-97f6-f705883f2c85.png)

### Option 1:-
Either We can simply write to enter Email id in login form so that it only accept for email id.

### Option 2:-
We can manipulate the code such that it can accept both number as well as email id for login Credential.

**Comment by mecskyverse** [comment]
Hey @Kanika637 can you assign this issue to me as a hactoberfest contribution.

**Comment by Kanika637** [comment]
thanks for opening the issue @mecskyverse, Go ahead🚀

**Comment by mecskyverse** [comment]
Hey @Kanika637 I was going through the feature to add phone number authentication but as this project's authentication is supported by firebase and when I researched about it I get to know I need to login in firebase account for which I need to login in google account of yours and which is not appropriate. To add phone number authentication in this project. I wanted your help to know if there is any other way or should I remove sentence of entering phone number something like this.
![image](https://user-images.githubusercontent.com/91150257/196510594-d1f7fd63-5a30-489e-9491-451a968a7e24.png)
