### ISSUE TITLE
Add social media icons

### ISSUE THREAD

**Issue by zugzwang03** [Kanika637/amazon-clone#124]
### Is your feature request related to a problem? Please describe.

![icons](https://user-images.githubusercontent.com/95460021/196038955-b275c2d7-9c1a-4908-9ddf-bfe6e1bd7d17.png)
if you look at the bottom, there is an image present, but I feel inclusion of some social media icons can feel up that bottom line beautifully.

### Describe the solution you'd like

I want to put in some social media icons there. If the admin wants to put in their own profiles, they can forward the link to me, will add it too.

**Comment by Kanika637** [comment]
@zugzwang03  actually we are trying to achieve maximum similarity with amazon's website. so, adding any social icons would not be appropriate.

**Comment by zugzwang03** [comment]
Yeah that is true, what do you wish to do with the logo part then?
