### ISSUE TITLE
Add back to top "button"

### ISSUE THREAD

**Issue by zugzwang03** [Kanika637/amazon-clone#125]
### Is your feature request related to a problem? Please describe.

![icons](https://user-images.githubusercontent.com/95460021/196039119-baaa0a3b-ff21-4c6a-b717-f3c48050eeed.png)
The back to top column is beautiful and efficient, but I feel like that column can only be accessed once you reach the end page, but in case if you want to move to top from any middle portion of the website, you need to use the scroll bar for that. 

### Describe the solution you'd like

I feel adding a button which will be visible all throughout, can make the solution for the above problem.
It looks something like this arrow: 
https://user-images.githubusercontent.com/95460021/194382371-fff5c2be-c459-483f-9ba7-ce370044d052.png
I can design and customize it accordingly as per the designing of the website.

**Comment by Kanika637** [comment]
Thanks for opening the issue @zugzwang03, but I think we don't require this functionality till now on the website.
