### ISSUE TITLE
Subtotal Container floating on top of the footer

### ISSUE THREAD

**Issue by Adithya-Sr** [Kanika637/amazon-clone#132]
### Describe the bug

No Response

### Expected behaviour

Expected to be in the same place

### Screenshots

 

https://user-images.githubusercontent.com/97578285/196969299-3295f2e1-c6d5-4037-9d91-16a201b2915b.mp4

### Additional context

No Response

**Comment by Adithya-Sr** [comment]
Hey @Kanika637  , can you please assign this to me?

**Comment by Kanika637** [comment]
Thanks for opening the issue @Adithya-Sr. Go ahead🚀
