### ISSUE TITLE
prettier config file

### ISSUE THREAD

**Issue by Shubhamsahu19** [Kanika637/amazon-clone#133]
### Is your feature request related to a problem? Please describe.

everyone uses prettier code formatter , so everyone has different global prettier configuration, which leads to multiple unnecessary changes in file. So having a local prettierrc and prettierignore can eliminate these unnecessary changes.

### Describe the solution you'd like

I will do it.

**Comment by Kanika637** [comment]
Thanks for opening the issue @Shubhamsahu19. Go ahead🚀
