### ISSUE TITLE
Some enhancements in the shopping cart page

### ISSUE THREAD

**Issue by Kanika637** [Kanika637/amazon-clone#140]
### Is your feature request related to a problem? Please describe.

There are some enhancements which we want to be listed here in the shopping cart page.

### Describe the solution you'd like

1. First, the background of the shopping page should be grey as on amazon's website. But the subtotal box and the shopping cart part's background colour should be white only. Take reference from this image👇

**Expected Behaviour**

![image](https://user-images.githubusercontent.com/84350895/197374951-6d9abf1a-26b4-494d-a48b-0a419f05e2ff.png)

**Current Behaviour**

As you can see, everything is white

![image](https://user-images.githubusercontent.com/84350895/197374986-61259d08-0ea1-41ef-81cf-232f3fca722d.png)

2. Second, "Hello, Your Shopping Basket" should be replaced by "Shopping Cart"

**Expected Behaviour**

![image](https://user-images.githubusercontent.com/84350895/197375031-b6f0fd51-2c45-4d94-b25b-4ea77bb39900.png)

**Current Behaviour**

![image](https://user-images.githubusercontent.com/84350895/197375045-129378eb-14c3-40c8-b82d-10d5b259684e.png)

3. The font size and family have to be changed

**Expected Behaviour**

![image](https://user-images.githubusercontent.com/84350895/197375093-e84662c1-0e70-445c-932d-30b010603331.png)

**Current Behaviour**

![image](https://user-images.githubusercontent.com/84350895/197375088-e41c8f01-f5a8-4cf8-baf2-e3cf5e47454e.png)

5. Pricing's styling should be changed

**Expected Behaviour**

![image](https://user-images.githubusercontent.com/84350895/197375207-38305945-ddaf-4a75-b813-c58661d55ea8.png)

**Current Behaviour**

![image](https://user-images.githubusercontent.com/84350895/197375219-1cf8460b-bea1-4241-883d-fff81d81c300.png)

**Comment by Rounak-28** [comment]
@Kanika637 can I work on this?

**Comment by jeet-09** [comment]
Hey I can help you with this issue. please assign it to me.

**Comment by J0SAL** [comment]
let me work on this issue.

**Comment by Jasleen-001** [comment]
Hi ,please assign this issue to me

**Comment by Kanika637** [comment]
I would like to address this issue that, according to open source guidelines, you should first make the issue assigned to yourself and then should make the PR.

Since @J0SAL has done all the work and made the PR (which is against the guidelines, but still), I am assigning the issue to him, but do take care of this next time.

@Jasleen-001 @Rounak-28 @jeet-09 sorry for this, but we have more issues, you can work on them.
