### ISSUE TITLE
Show More Products Button

### ISSUE THREAD

**Issue by Shivam-Katare** [Kanika637/amazon-clone#142]
### Is your feature request related to a problem? Please describe.

Hey, @Kanika637. I'm considering adding a "Load More" button on the homepage.

### Describe the solution you'd like

There are some products on the site, and after those, there should be a **Load More** button so that if the user wants to see more things, they may click on it and see the rest of the products.

**Comment by Kanika637** [comment]
Thanks for opening the issue @Shivam-Katare , Go ahead🚀
