### ISSUE TITLE
Side navbar enhancement

### ISSUE THREAD

**Issue by Kanika637** [Kanika637/amazon-clone#144]
### Is your feature request related to a problem? Please describe.

Some font size and family has to be changed for the side navbar

### Describe the solution you'd like

**Current Behaviour**

1. ![image](https://user-images.githubusercontent.com/84350895/197388422-317211f7-28ed-48b5-9f2a-14baa3fff438.png)

2. ![image](https://user-images.githubusercontent.com/84350895/197388536-a66b85f2-6626-4dcf-a92a-096fb71c7742.png)

**Expected Behaviour**

1. ![image](https://user-images.githubusercontent.com/84350895/197388463-557d5c1f-b1d3-4555-b7ba-7f8b54376146.png)

3. ![image](https://user-images.githubusercontent.com/84350895/197388548-1baa8dd4-b207-4f86-bf7a-2c1c0d720053.png)

**Note**: After Hello, the user's name should be dynamic

**Comment by Shivam-Katare** [comment]
Hey @Kanika637. Can I work on this issue?

**Comment by Jasleen-001** [comment]
Hey ,please assign this issue to me

**Comment by Kanika637** [comment]
Hey @Shivam-Katare, since you are already working on a current issue. So assigning the issue to you @Jasleen-001 🚀

**Comment by Shivam-Katare** [comment]
> Hey @Shivam-Katare, since you are already working on a current issue. So assigning the issue to you @Jasleen-001 🚀

Okay. Sure.

**Comment by Kanika637** [comment]
Any updates @Jasleen-001 ?

**Comment by Yashkhamkar** [comment]
can you assign this to me

**Comment by prnvtripathi** [comment]
hey @Kanika637, i can work on it

**Comment by Kanika637** [comment]
Go ahead @prnvtripathi 🚀

**Comment by aklite** [comment]
Hi can you assign this to me ? @Kanika637

**Comment by Kanika637** [comment]
> Go ahead @prnvtripathi 🚀

Any updates @prnvtripathi ?

**Comment by prnvtripathi** [comment]
Yeah, i did the font updates but, can't get the hold of user name thing 🥲
