### ISSUE TITLE
Login Form Broken Link

### ISSUE THREAD

**Issue by mecskyverse** [Kanika637/amazon-clone#147]
### Describe the bug

In the login Form Conditions of use, link is broken. On clicking it links to the Home page like you can see in the video.
https://www.loom.com/share/d395ddc7cac04b0dbb372585692f14ae

But in Code
![image](https://user-images.githubusercontent.com/91150257/197844549-479cebfc-dfd9-48c5-9e7a-d69065831669.png)
there is an anchlink variable present which links to Amazon's Condition of use

![image](https://user-images.githubusercontent.com/91150257/197844681-5e8d2f1a-ae15-4cb0-b582-c49faa1b6a8c.png)

### Expected behaviour

It should Redirect to this link.
https://amazon.in/gp/help/customer/display.html/ref=ap_signin_notification_condition_of_use?ie=UTF8&nodeId=200545940

**Comment by mecskyverse** [comment]
Hey! @Kanika637 can you checkout this issue and if it is correct than can you assign it to me.

**Comment by Kanika637** [comment]
Thanks for opening the issue @mecskyverse .Go ahead🚀
