### ISSUE TITLE
Side-Nav Closing issue

### ISSUE THREAD

**Issue by mecskyverse** [Kanika637/amazon-clone#149]
### Describe the bug

In Navbar after Clicking on All, Sidebar is visible 
![image](https://user-images.githubusercontent.com/91150257/198545298-c695b5bc-71cf-42c3-af23-678e62ed9560.png)
In sideBar, the closing button is overlapping on the scroll bar of the SideBar. This makes it a problem to close the Sidebar which you can see in this video.
![image](https://user-images.githubusercontent.com/91150257/198547289-a3f46b04-4ecd-4aa3-8249-b7c1cd6d2af4.png)

https://www.loom.com/share/ec62425c18134dbcb38d59f80144997d

while clicking at X button scrollbar is clicking and you have to click at the leftmost corner of the X button to make it work.

### Expected behaviour

Side-Nav-head and Side-Nav-body should have some CSS changes to make it work like this.
![image](https://user-images.githubusercontent.com/91150257/198547667-57ab946e-7ca4-48fa-a990-6e2c53b63af4.png)

For Now Side-Nav-head and Side-Nav-body have common CSS class named Side-Nav which is causing the problem.

**Comment by mecskyverse** [comment]
Hey! @Kanika637 I have completed my other issues can you assign me this issue as the hactoberfest's last date is near?

**Comment by Kanika637** [comment]
Hey @mecskyverse, Thanks for opening the issue. Go ahead🚀
