### ISSUE TITLE
Render the products in "Shop By Category" section dynamically

### ISSUE THREAD

**Issue by Adithya-Sr** [Kanika637/amazon-clone#152]
### Is your feature request related to a problem? Please describe.

Currently the products are rendered like this:
![image](https://user-images.githubusercontent.com/97578285/201474271-dfc99d48-db28-4548-81ad-f0d262694291.png)

### Describe the solution you'd like

I would like to render the products dynamically .

**Comment by Adithya-Sr** [comment]
Can I work on this one?

**Comment by Kanika637** [comment]
Hey @Adithya-Sr  Thanks for opening the issue. Go ahead!
