### ISSUE TITLE
Deploy the project

### ISSUE THREAD

**Issue by VenomFate-619** [Kanika637/amazon-clone#155]
### Is your feature request related to a problem? Please describe.

I need to view the project without cloning

### Describe the solution you'd like

Deploy on netlify , it will also provide PR preview

**Comment by Kanika637** [comment]
Go ahead @VenomFate-619 ✅. It's good to have it on netlify along with the Docker image we already have.

**Comment by Kanika637** [comment]
Any updates @VenomFate-619 ?

**Comment by VenomFate-619** [comment]
sorry, forget to update.
I had deployed it on netlify but getting a white screen and error in the console

![image](https://user-images.githubusercontent.com/67755128/207236926-e70cffbd-e611-45c5-96bb-d68f478c3ff8.png)

**Comment by VenomFate-619** [comment]
sorry, forget to update you.

https://dulcet-scone-d98f2d.netlify.app/

deployed URL

**Comment by VenomFate-619** [comment]
I would recommend deploying the project yourself because currently, the deployed site is linked to my fork repo.
So whenever I pull or commit then only it will be updated.

you can have a look at my forked repo what changes need to be made to deploy it on netlify.

https://github.com/VenomFate-619/amazon-clone
