### ISSUE TITLE
Sign in button for few seconds 

### ISSUE THREAD

**Issue by aklite** [Kanika637/amazon-clone#158]
### Is your feature request related to a problem? Please describe.

when user is logged in sign in button is hidden
![image](https://user-images.githubusercontent.com/118159735/207010629-0853e166-5359-4a4a-be54-fa938473cb47.png)

when user is logged out sign in button shows up for about 7 seconds 
![image](https://user-images.githubusercontent.com/118159735/207011016-db8c0fe9-2bf7-49ae-a216-cae3785beea1.png)

### Describe the solution you'd like

We can use useEffect and  setTimeout javascript function to create this

**Comment by aklite** [comment]
sorry @Kanika637 for not first assigning this task to self I felt like If couldn't complete I would get removed so I tried working first

**Comment by Kanika637** [comment]
That is fine @aklite , but don't repeat that again🙌
