### ISSUE TITLE
meta tags to all the pages and in required places

### ISSUE THREAD

**Issue by aklite** [Kanika637/amazon-clone#161]
### Is your feature request related to a problem? Please describe.

Title should change for different pages, different urls and in places required .

## title 
for the home page **title** could be  "Online Shopping site clone in India: Shop Online using Amazon's clone for Mobiles, Books, Watches, Shoes and More - Amazon-clone.in"

## description 
**description** could be Amazon-clone.in: Online Shopping India - Buy mobiles, laptops, cameras, books, watches, apparel, shoes and e-Gift Cards. Free Shipping & Cash on Delivery Available.

## keywords
keywords using meta 

these would be the mains things currently I am thinking of adding and if needed more things related to meta

**Comment by Kanika637** [comment]
Go ahaed @aklite 🚀

**Comment by aklite** [comment]
hii @Kanika637 have a look please 😁✌🏻
