### ISSUE TITLE
npm i is not working in after fork and clone to this repositores

### ISSUE THREAD

**Issue by athifbinu** [Kanika637/amazon-clone#163]
### Describe the bug

I Want To Contribute to This Project I am following this this steps
*git fork in this repository
*git clone
*cd amazon clone
*npm i but is not working amazon 

### Expected behaviour

npm dependencies are not install

### Screenshots

![Screenshot from 2023-02-10 10-21-50](https://user-images.githubusercontent.com/85118365/218004732-f611578f-47f0-447b-817f-bba81bd0e728.png)

**Comment by Kanika637** [comment]
Try entering the command `npm install --legacy-peer-deps`

**Comment by athifbinu** [comment]
Thanks
