### ISSUE TITLE
Images lack alt props

### ISSUE THREAD

**Issue by Adithya-Sr** [Kanika637/amazon-clone#17]
**A lot of image tags in the codebase don't have an alt prop** 
 
![image](https://user-images.githubusercontent.com/97578285/185763460-3624a560-214c-4e55-a7c2-868a64c5a953.png)

**Comment by Kanika637** [comment]
Thanks for opening the issue @Adithya-Sr , Let's see if anyone else wants to work on this issue

**Comment by ItzNesbroDev** [comment]
I would like to work on this issue

**Comment by Kanika637** [comment]
Here you go @ItzNesbroDev 👍
