### ISSUE TITLE
Shopping basket page's top cover image is not in correct size

### ISSUE THREAD

**Issue by Kanika637** [Kanika637/amazon-clone#19]
**Previous Behaviour**

![image](https://user-images.githubusercontent.com/84350895/186074541-494be312-f9e3-4d69-b8cf-322f4dc233f2.png)

### Fix the top cover image so that both the image and the subtotal dialog box should be properly aligned.

**Comment by KhanyaMateta** [comment]
Can you provide more details? Do you want the cover page to be size of the whole view width and view height?

**Comment by Kanika637** [comment]
Yes @KhanyaMateta , so we want that the cover image and that dialog box should be aligned properly without any space between them.

**Comment by AnkanHalder** [comment]
Here are some of the designs. I am not sure exactly what we are going for.  Can you point me in a direction ?

Test 5

![type5](https://user-images.githubusercontent.com/93651434/186588181-b82bb838-e572-48ae-8b12-cb5af94bc807.png)

Test 4
![type4](https://user-images.githubusercontent.com/93651434/186588199-b80a8ea3-524e-4da2-b297-715074c72784.png)

Test 3
![type3](https://user-images.githubusercontent.com/93651434/186588209-c83e29f1-5fee-4f43-a5e1-634895cf4a5c.png)

Test 2
![type2](https://user-images.githubusercontent.com/93651434/186588210-66101b7c-16ee-400f-aa35-390b5820adf2.png)

Test 1
![type1](https://user-images.githubusercontent.com/93651434/186588213-5e418644-6435-46a4-b79a-c6db916fd1cb.png)


If there is something else entirely you are looking for please let me know

**Comment by Kanika637** [comment]
Great work @KhanyaMateta, I think the third one looks perfect, just try to find a different image so that it can fit well.

**Comment by kakkarot0** [comment]
Hey can I work on this issue

**Comment by Jai-Solania-29** [comment]
Hey We are looking for a different design now hence closing this issue ✅
