### ISSUE TITLE
Change the design of search bar

### ISSUE THREAD

**Issue by Kanika637** [Kanika637/amazon-clone#26]
*Previous Behaviour*

![image](https://user-images.githubusercontent.com/84350895/188300476-155a0a9b-3f95-438d-8d08-4a9f5ddc4565.png)

*Desired Behaviour*

![image](https://user-images.githubusercontent.com/84350895/188300464-43a30583-bc95-4a62-8244-207561bad801.png)

**Comment by Adithya-Sr** [comment]
I would like to work on this one!

**Comment by Kanika637** [comment]
Go ahead @Adithya-Sr 👍

**Comment by Adithya-Sr** [comment]
Thanks @Kanika637 !

**Comment by Adithya-Sr** [comment]
hey @Kanika637  ,I designed the navbar but its a bit different from what you've asked :

https://user-images.githubusercontent.com/97578285/188925753-03176e2e-4c69-4cab-a209-1057eb159fa2.mp4

Just wanted to know whether this design is fine or should I revert to the design you wanted

**Comment by AditSaxena** [comment]
Hi
I would like to work on this issue.

**Comment by Adithya-Sr** [comment]
Hey  @AditSaxena  , I am sorry but this isssue is assigned to me.

**Comment by Jai-Solania-29** [comment]
Hey @Adithya-Sr, Great Work🎉
But the thing is that we want to achieve maximum similarity with the real amazon site. So kindly try to make it the same as given in the screenshot.
Kindly take reference from https://www.amazon.com/ 🚀

**Comment by Jai-Solania-29** [comment]
Also, try to make the search bar just like this as we want to incorporate other things on the navbar as well.

![image](https://user-images.githubusercontent.com/90816300/190131235-3e52f8a8-7fb1-4b2b-8688-ff8bc948441d.png)

**Comment by Adithya-Sr** [comment]
@Jai-Solania-29  Sure ,I'll design it that way👍

**Comment by Jai-Solania-29** [comment]
> Hi I would like to work on this issue.

Hey, @AditSaxena Feel free to work on other issues which are not assigned to someone yet😃

**Comment by Jai-Solania-29** [comment]
> @Jai-Solania-29 Sure, I'll design it that way👍

Cool, Go ahead and feel free to ping me if you face any confusion.

**Comment by Adithya-Sr** [comment]
@Jai-Solania-29  sure!

**Comment by Adithya-Sr** [comment]
@Jai-Solania-29 I implented the  basic design of the navbar but I couldn't figure out how to implement the functionality in the 'select' component .I tried googling the problem and found a solution but it was in JQuery. Can I get any help?
![image](https://user-images.githubusercontent.com/97578285/191514005-fedbad01-a606-43e6-a00e-cf60152c250f.png)

**Comment by Jai-Solania-29** [comment]
@Adithya-Sr, Some changes I would like to suggest to you:
-> Don't worry about the functionality, that is a completely new issue✅
-> Just design the UI part and make your PR🚀
-> Just do some more research on how you can implement it and then open a new issue for that and then you can start working on that🚀

**Comment by Adithya-Sr** [comment]
@Jai-Solania-29 sorry for the late reply, sure i'll do the same👍
