### ISSUE TITLE
Add more products on the home page

### ISSUE THREAD

**Issue by Kanika637** [Kanika637/amazon-clone#27]
*Current Behaviour*

![image](https://user-images.githubusercontent.com/84350895/188300535-fdc6b773-e954-42e2-9257-eeaf58bdfacd.png)

Add more products on the home page in the same fashion as it is there.

**Comment by lazyturd** [comment]
hey, can i be assigned to this. i would like to help

**Comment by Kanika637** [comment]
Sure go ahead @lazyturd 🚀

**Comment by Kanika637** [comment]
@lazyturd, any updates?

**Comment by lazyturd** [comment]
> @lazyturd, any updates?

No, i'm sorry. I am not very good with react so I was trying to learn while solving the issue, you can unassign me. Again, i am very sorry

**Comment by Kanika637** [comment]
That is completely fine @lazyturd. 
The main motive for this project is for people to learn by doing. If you are still learning, go ahead, take your time and then complete the issue 💯

**Comment by Jai-Solania-29** [comment]
Any updates @lazyturd ?

**Comment by uvsingh2706** [comment]
hey @Kanika637 can you assign this work to me, i can work on this part

**Comment by Kanika637** [comment]
Due to inactivity from @lazyturd , @uvsingh2706  you are being assigned the issue🚀

**Comment by uvsingh2706** [comment]
oky @Kanika637 , I will try to complete it
