### ISSUE TITLE
Change Cursor to Pointer

### ISSUE THREAD

**Issue by Jai-Solania-29** [Kanika637/amazon-clone#28]
While hovering on the Add to Basket button it shows the default cursor, Which needs to be changed to the Pointer cursor.

Current Behaviour : 

![image](https://user-images.githubusercontent.com/90816300/189715994-125ab85f-37cd-43ee-b3a0-4d6d3dd21baa.png)

Expected Behaviour : 

![image](https://user-images.githubusercontent.com/90816300/189715772-43321e65-3df1-4bd8-9530-7a4ea0e71a3b.png)

**Comment by keishaharris** [comment]
I'll fix this!

**Comment by abitsalihu** [comment]
@Jai-Solania-29 I would like to work on this issue.

**Comment by Farhan-Ali2002** [comment]
I'll try to fix this.

**Comment by Jai-Solania-29** [comment]
Hey there! Thanks for showing interest, but @keishaharris was the first one to comment so according to the FCFS approach I'm assigning this issue to @keishaharris for now.
You guys can work on some other issues ✌️.
