### ISSUE TITLE
Remove the Underline from the Hello, Sign In option in the Header

### ISSUE THREAD

**Issue by Jai-Solania-29** [Kanika637/amazon-clone#29]
Remove the Underline from the Hello, Sign In option in the Header.

![Screenshot 2022-09-12 224943](https://user-images.githubusercontent.com/90816300/189717249-bc318188-078e-446a-83ef-530941518422.png)

**Comment by hemant-sw** [comment]
Hey @Jai-Solania-29 can I fix these issue.

**Comment by Jai-Solania-29** [comment]
Yes, please!!
