### ISSUE TITLE
Change the Favicon of the Project

### ISSUE THREAD

**Issue by Kanika637** [Kanika637/amazon-clone#3]
Change the React Logo to the official Amazon Logo.

**Comment by aaqilrk** [comment]
Please assign this issue to me. I'll make the necessary changes.

**Comment by Kanika637** [comment]
Thank you for your interest. Yes sure, go ahead :)

**Comment by ItzNesbroDev** [comment]
@Kanika637 Assign Me To This Issue.

**Comment by Kanika637** [comment]
It's been assigned to @aaqilrk, go ahead check out some more issues

**Comment by aaqilrk** [comment]
I have followed the project setup as instructed. While running `npm i` I am receiving the following error.
<img width="521" alt="image" src="https://user-images.githubusercontent.com/75661314/185395266-2d5ad43b-004b-4d6a-b32b-1b05861b0040.png">

**Comment by Kanika637** [comment]
Try this `npm i --force`

**Comment by aaqilrk** [comment]
Yes, this fix is working but it is making changes to the package-lock.json file so would have to make a new branch and then run this command. Could you also explain why this error is occurring?

**Comment by Kanika637** [comment]
Well, It will not make any major changes in the package-lock.json file and I am figuring out why this error is coming.

**Comment by aaqilrk** [comment]
Okay, thanks for letting me know.
