### ISSUE TITLE
Change the Size and Position of the Amazon logo in navbar

### ISSUE THREAD

**Issue by Jai-Solania-29** [Kanika637/amazon-clone#32]
**Current Behaviour**

![image](https://user-images.githubusercontent.com/90816300/190130235-8b7a899a-8642-4471-97df-8123c30dc98d.png)

**Desired Behaviour**

![image](https://user-images.githubusercontent.com/90816300/190130344-41c51081-c85c-4c53-8b78-6d2d86c20a17.png)

**Description**

Kindly note that you have to just change the position of the logo (i.e towards the left) and also increase the size of the logo.

**Comment by abitsalihu** [comment]
Hey, I would like to work on this issue! :)

**Comment by Jai-Solania-29** [comment]
Sure, Go ahead 🚀

**Comment by Jai-Solania-29** [comment]
#35
