### ISSUE TITLE
New enhancement in the design

### ISSUE THREAD

**Issue by Jai-Solania-29** [Kanika637/amazon-clone#33]
**Description**

We want to add a new enhancement to the design which is this:

![image](https://user-images.githubusercontent.com/90816300/190132667-fac110aa-1c86-4bee-b33d-d9279e1d2431.png)

Make sure that you add it right below the Navbar with no gap in between.
Take reference from here https://www.amazon.com/ 🚀

**Desired Behaviour**

![image](https://user-images.githubusercontent.com/90816300/190133134-9e16a4e7-b3fa-4fb5-b5ec-d12b505c2be2.png)

**Note**: Don't make any changes in the Navbar, Just work on the enhancement.

**Comment by abitsalihu** [comment]
Hey I would like to work on this issue. :)

**Comment by developer-irfan** [comment]
@Jai-Solania-29 assign me this task, i will enhance this as per your requirements.

**Comment by Jai-Solania-29** [comment]
Hey, @developer-irfan Thanks for showing interest, You can start working on this 🚀
Assigning the issue to you ✅

**Comment by Jai-Solania-29** [comment]
Any updates @developer-irfan ?
