### ISSUE TITLE
Carousel needed

### ISSUE THREAD

**Issue by Jai-Solania-29** [Kanika637/amazon-clone#34]
Currently, there is only one image, and that too static.

**Current Behaviour**

![image](https://user-images.githubusercontent.com/90816300/190133947-376166ee-5ba0-4568-bd38-7e322f9bc78b.png)

**Desired Behaviour**

![image](https://user-images.githubusercontent.com/90816300/190135357-c22f3c63-da13-482b-9d28-c59da7e5dccd.png)

![image](https://user-images.githubusercontent.com/90816300/190135500-cf947bae-4605-4490-96c3-a110034f555c.png)

We need a dynamic carousel instead of a static picture.
Take reference from here https://www.amazon.com/ 🚀

**Comment by sdeepanshu17** [comment]
Please assign this to me.

**Comment by karanpatel2329** [comment]
Can you assign to me,
I had already worked on it. 
Here is my portfolio site [www.karannpatel.com](www.karannpatel.com)

**Comment by Kanika637** [comment]
Well, It's a First Come First Serve rule, So @sdeepanshu17  you are being assigned the issue🚀

And @karanpatel2329  Go ahead, there are so many other issues you can find and work on them.
