### ISSUE TITLE
Change the cart icon

### ISSUE THREAD

**Issue by uvsingh2706** [Kanika637/amazon-clone#38]
Can i change the cart icon at the top right corner  of header to which is present at amazon actual website 
https://icon-library.com/icon/shopping-icon-on-amazon-25.html

**Comment by Kanika637** [comment]
Hey @uvsingh2706, Thanks for opening the issue.
Can you please share a little sample of the work you want to add?

**Comment by uvsingh2706** [comment]
oky @Kanika637, i'm working on it

**Comment by uvsingh2706** [comment]
<img width="1421" alt="Screenshot 2022-09-21 at 10 02 23 AM" src="https://user-images.githubusercontent.com/85758285/191415091-fa623f4d-62fc-46da-a9d9-59cfa7f2f314.png">

After changing the cart icon the final header will look like this, is it okay ?

**Comment by Jai-Solania-29** [comment]
Yes, it's looking good, Go ahead and make your changes 🚀
