### ISSUE TITLE
Try to give a design for the footer 

### ISSUE THREAD

**Issue by Kanika637** [Kanika637/amazon-clone#4]

**Comment by lmash12** [comment]
hey can i work on this?

**Comment by Kanika637** [comment]
Sure @lmash12, Go ahead👍
As it is a clone of amazon, try to design the footer just like that✅

**Comment by Kanika637** [comment]
Hey @lmash12, any updates on the footer?
If you have any doubts feel free to ask me✌️

**Comment by Jai-Solania-29** [comment]
Hey, @lmash12 due to your inactivity I'm unassigning this issue to you.

**Comment by ramyashreeshetty** [comment]
Hey team, actually working with issue and almost done with it. But I m facing problem with an image. My image isn't getting displayed on the localhost. Any method to resolve it?

**Comment by ramyashreeshetty** [comment]
![image](https://user-images.githubusercontent.com/43513353/190727217-58a79cd2-a2d9-4972-aa13-dee8c04b2f5c.png)

thts the issue

**Comment by ramyashreeshetty** [comment]
umm i tried svg and png both, tried a url it worked in some cases and some it didnt

**Comment by Jai-Solania-29** [comment]
Hey, @ramyashreeshetty Actually, I can't help you with this issue without seeing the actual code, so just do one thing Push your changes and make a PR for now, and then I'll open separate issues for the remaining work in the footer if any.

**Comment by ramyashreeshetty** [comment]
Okay got it.

**Comment by Jai-Solania-29** [comment]
Also in future, Please make the issue assigned to yourself first before you finally start working on the issue.
