### ISSUE TITLE
Navbar functionality implemetation 

### ISSUE THREAD

**Issue by Adithya-Sr** [Kanika637/amazon-clone#46]
## Current Behaviour :
Currently the navbar is static and doesn't have any selecting functionality.
 
## Desired Behaviour :
Implementation of  a select-bar as in the original Amazon site.
![image](https://user-images.githubusercontent.com/97578285/192574208-8df99ea0-47b1-4cc1-a868-fdfad1d7ce60.png)

**Comment by Kanika637** [comment]
Hey @Adithya-Sr  Thanks for opening the issue, do you want to work on this issue?

**Comment by Adithya-Sr** [comment]
Sure @Kanika637 !

**Comment by Kanika637** [comment]
Go ahead @Adithya-Sr 🚀

**Comment by Kanika637** [comment]
Any updates @Adithya-Sr?

**Comment by Adithya-Sr** [comment]
Really sorry for the late response @Kanika637 , I started working on the issue about 2 days ago but couldn't make much progress on it . If I don't make a pull request by today , You can assign it to someone else . I get it that I took a lot of time for this  ,sorry for that .I was stuck in a busy schedule, Hope you understand.

**Comment by Adithya-Sr** [comment]
I completed upto this :

https://user-images.githubusercontent.com/97578285/194028564-bda16520-bff3-4ec0-933f-8e84919901ee.mp4

couldn't get that dynamic space allocation between the select component and the input component.

**Comment by Jai-Solania-29** [comment]
> Really sorry for the late response @Kanika637 , I started working on the issue about 2 days ago but couldn't make much progress on it . If I don't make a pull request by today , You can assign it to someone else . I get it that I took a lot of time for this ,sorry for that .I was stuck in a busy schedule, Hope you understand.

Okay, @Adithya-Sr, We understand your concern, so what we can do is, just respond by today if you can complete the issue else we can assign it to somebody else.

**Comment by ozair-dev** [comment]
I'd like to work on this issue. Assign it to me.

**Comment by Kanika637** [comment]
Great @ozair-dev , Go ahead🚀
