### ISSUE TITLE
Header is not complete

### ISSUE THREAD

**Issue by uvsingh2706** [Kanika637/amazon-clone#48]
<img width="1413" alt="Screenshot 2022-09-28 at 7 12 08 PM" src="https://user-images.githubusercontent.com/85758285/192794889-66b706b2-a8a5-4a7e-8b58-30b83586906c.png">

hey @Kanika637 can you assign this issue to me, i can make the  final header look alike the above i have mentioned

**Comment by Kanika637** [comment]
Hey @uvsingh2706, You can go forward and work on this issue.

One more thing, the content of the product's text is being misplaced, Kindly correct it

![image](https://user-images.githubusercontent.com/84350895/192803023-a95e1637-3799-4b7e-b7ed-7296661e2843.png)

**Comment by uvsingh2706** [comment]
oky!! 
i'm doing it

**Comment by Kanika637** [comment]
Hey @uvsingh2706, Regarding handling the misplaced, don't do that as someone is already working on it as a new issue. Just complete that grey header👍

**Comment by uvsingh2706** [comment]
oky @Kanika637
