### ISSUE TITLE
Alignment of header components

### ISSUE THREAD

**Issue by Kanika637** [Kanika637/amazon-clone#49]
**Describe the bug**
The alignment of header components is not right

**Current Behaviour**
![image](https://user-images.githubusercontent.com/84350895/192803913-b2130464-5bfb-4824-b6b1-8823254339ee.png)

**Expected behaviour**
Shift the search bar a little to the left, so that the cart icon and other components can be placed correctly

**Additional context**
Do share screenshots of the work you do while making the PR.

**Comment by Kanika637** [comment]
Hey @Mustafa-Azad025, You can check out the issues section, we do have stuff related to frontend🚀

**Comment by sdeepanshu17** [comment]
Please assign this to me.

**Comment by Rounak-28** [comment]
@Kanika637 can I work on this issue?

**Comment by karanpatel2329** [comment]
I am willing to work on it. Please assign to me.

**Comment by siddharth1009maker** [comment]
Hi, @Kanika637  I would like to work on this issue.

**Comment by Kanika637** [comment]
Deciding this according to First Come First Serve basis, @Rounak-28 you are being assigned the issue🚀

**Comment by Kanika637** [comment]
@karanpatel2329  and @siddharth1009maker, there are many other issues which you can find and start working on them🚀

**Comment by Rounak-28** [comment]
@Kanika637 whole site is looking broken on my laptop.

![Screenshot 2022-09-29 145445](https://user-images.githubusercontent.com/95576871/192995032-58c94a7a-8a02-4fbf-b117-a90a6cb1658b.jpg)

**Comment by Kanika637** [comment]
Hey @Rounak-28 , someone is already working on this broken part as an issue✌️

**Comment by Rounak-28** [comment]
Okay! 
Should I fix that header component now or wait for them to complete?
Reducing searchBar width will fix this issue.

**Comment by Kanika637** [comment]
Yes, @Rounak-28, you can start with this, I think changing the width of header components will not affect other issues👍
