### ISSUE TITLE
Change the design of "Add to Basket" button

### ISSUE THREAD

**Issue by Kanika637** [Kanika637/amazon-clone#5]
Current Behaviour
![image](https://user-images.githubusercontent.com/84350895/185344067-0607b3ff-792a-4482-a289-a12c3ba955e9.png)

We want this button to look little more presentable.

**Comment by anuragh2002** [comment]
Hey @Kanika637 can I work on this issue? Also, how do I run your project on my local system?

**Comment by Kanika637** [comment]
Here u go @anuragh2002 👍

**Comment by anuragh2002** [comment]
Yeah I tried "npm i". But it is showing no such command.
![Screenshot (718)](https://user-images.githubusercontent.com/78635306/185383172-54f6a985-6565-42d4-bbbb-85f0d255da66.png)

**Comment by Kanika637** [comment]
Its because maybe you don't have Node.js installed in your system

**Comment by uvsingh2706** [comment]
Hey @Kanika637 can I work on this issue? Also, i can do it easily

**Comment by Jai-Solania-29** [comment]
Hey, @anuragh2002 any updates?

**Comment by Jai-Solania-29** [comment]
> Hey @Kanika637 can I work on this issue? Also, i can do it easily

Hey, @uvsingh2706 thanks for showing interest, Let me clear things with Anurag first and then I'll get back to you 😃.

**Comment by anuragh2002** [comment]
> Hey, @anuragh2002 any updates?

Hey @Jai-Solania-29 I worked on this issue and created a pull request which has been merged!

https://github.com/Kanika637/amazon-clone/pull/15

**Comment by uvsingh2706** [comment]
@Jai-Solania-29 oky 🤗

**Comment by Jai-Solania-29** [comment]
> > Hey, @anuragh2002 any updates?
> 
> Hey @Jai-Solania-29 I worked on this issue and created a pull request which has been merged!
> 
> #15

Ok, @anuragh2002 thanks for your contribution 😃.
Also, Next time while making a PR  please mention the related issue in the PR as well.

**Comment by Jai-Solania-29** [comment]
> @Jai-Solania-29 oky 🤗

Hey, @uvsingh2706 this issue is closed, kindly please work on other issues.
