### ISSUE TITLE
Product's text being misplaced

### ISSUE THREAD

**Issue by Kanika637** [Kanika637/amazon-clone#50]
**Describe the bug**
The CSS of the product's information has been misplaced

**Current Behaviour**

![image](https://user-images.githubusercontent.com/84350895/192805974-5eba3af6-4d3d-4ccb-8ccf-9b5208b8113b.png)

**Expected behaviour**

![image](https://user-images.githubusercontent.com/84350895/192806080-82645efd-9fdf-4f48-8e84-7815e39a2010.png)

**Additional context**

Do share screenshots of the work you do while making the PR.

**Comment by najeebkp** [comment]
Hi, I would like to take this up. can you please assign me this task? @Kanika637

**Comment by Jai-Solania-29** [comment]
Thanks for showing interest @najeebkp, Go ahead you can start working on the issue 🚀

**Comment by najeebkp** [comment]
Hi @Jai-Solania-29. i couldn't run this app. it shows webpack error. then i troubleshooted. now it showing `Failed to compile.
./node_modules/@mui/styled-engine/index.js
Module not found: Can't resolve '@emotion/react'`

**Comment by Rounak-28** [comment]
Hey @najeebkp 
I also faced the same issue.
You can fix this by -
`npm i @emotion/react @emotion/styled`

**Comment by najeebkp** [comment]
Thanks @Rounak-28 
It works !!

**Comment by sunilgaddi** [comment]
I just saw this issue on the website, it is because the product card container max-height is set to 400px, which in turn making the text-overflow.

**Comment by Kanika637** [comment]
Hey @sunilgaddi, thanks for pointing out the error👍
@najeebkp You can take idea from this🚀
