### ISSUE TITLE
Add contributors in readme file

### ISSUE THREAD

**Issue by AnshuPathak-88825** [Kanika637/amazon-clone#51]

**Comment by AnshuPathak-88825** [comment]
I want to work on this pls assign me this issue

**Comment by Kanika637** [comment]
Hey, @AnshuPathak-88825  Could you please share some screenshots or samples of what do you actually want in the Readme file and then I can assign you the file?

**Comment by AnshuPathak-88825** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/78332454/192955508-06b47452-6cac-4a8e-94f8-89f38cd11e2a.png)
**like this**

**Comment by Kanika637** [comment]
Great! Assigning the issue to you @AnshuPathak-88825 🚀

**Comment by AnshuPathak-88825** [comment]
@Kanika637 pls merge my pr
