### ISSUE TITLE
Live link for the project

### ISSUE THREAD

**Issue by zabihhaqqani** [Kanika637/amazon-clone#53]
- Hey @Kanika637 Currently, there is no way to see the project live before running it on the local machine.
- The project could be hosted online and its live link can be added to the GitHub repo.

**Comment by Kanika637** [comment]
Hey @zabihhaqqani, Thanks for opening the issue. Actually, I am facing some errors in deploying the website, currently working on that. For now, you can use the GitPod extension rather than running it on your local machine🙌
