### ISSUE TITLE
containerize the project 

### ISSUE THREAD

**Issue by harshit0571** [Kanika637/amazon-clone#54]
hi!,
can i containerize the project using docker.
this would made it easier for others to set it up who uses docker.

**Comment by Kanika637** [comment]
Hey @harshit0571, That's great if you want to try this. I was also thinking of the same. Ping me if you get stuck or need any resources, would love to work together 🙌

**Comment by harshit0571** [comment]
there is also version problem in this project, it has react version 17.2.0 , that is older version.

**Comment by Kanika637** [comment]
Okay, will work on that

**Comment by harshit0571** [comment]
hi @Kanika637  what version of node js are you using for this project.
can you run node -v to check

**Comment by Kanika637** [comment]
Its `v16.17.1` @harshit0571

**Comment by harshit0571** [comment]
the latest version of nodejs is 18.9.1 .
the project will not work for people with higher nodejs version

**Comment by harshit0571** [comment]
i think we should write in the readme file to install node v16.17.1 to setup this project.

**Comment by Kanika637** [comment]
But do you think @harshit0571 , will it be good to downgrade the node version?👀

**Comment by harshit0571** [comment]
or we can upgrade the react version

**Comment by harshit0571** [comment]
i have created the Dockerfile for node 16.17.1 , it is working fine

**Comment by Kanika637** [comment]
Great @harshit0571 🙌

**Comment by harshit0571** [comment]
i will add the docker-compose file in some time and raise the pr.
Anyone will be able to run the project with it without downgrading nodejs
