### ISSUE TITLE
Enhance the Navbar

### ISSUE THREAD

**Issue by Shivam-Katare** [Kanika637/amazon-clone#59]
The website's navbar is not responsive, and there are numerous gaps between the texts. I want to enhance the navbar by fixing padding, gaps, and responsiveness.

### Currently Look Like

![Screenshot (62)](https://user-images.githubusercontent.com/91705825/193211872-32e76bd6-12e6-4c54-bdd3-0bd5c82539d7.jpg)

### After Changes done

![Screenshot (63)](https://user-images.githubusercontent.com/91705825/193212153-1137246b-3cc2-487f-a84a-4264cf9def04.png)

Hey @Kanika637, let me know if it looks good to you, and if it looks good, then assign this issue to me, and I will start working.

**Comment by Kanika637** [comment]
Hey @Shivam-Katare, Thanks for opening the issue 🙌 but someone is already working on this issue and have also made a PR.

**Comment by Jai-Solania-29** [comment]
ok so closing the issue ✅
