### ISSUE TITLE
<add CONTRIBUTING.md file>

### ISSUE THREAD

**Issue by Kanika637** [Kanika637/amazon-clone#6]
The readme contains the contributing guidelines, but a doc is needed for listing all the steps which include:

1. How to make a PR?
2. How to open new issues?

**Comment by Aahil13** [comment]
I think I'm a great fit for this @Kanika637 😎

**Comment by Kanika637** [comment]
Go ahead @Aahil13 👍

**Comment by Aahil13** [comment]
On it!
