### ISSUE TITLE
Fix the CSS of Sign In

### ISSUE THREAD

**Issue by Jai-Solania-29** [Kanika637/amazon-clone#60]
**Describe the bug**
Sign In page not looking presentable, Some minor changes in the CSS needs to be done.

**Current behavior**

![image](https://user-images.githubusercontent.com/90816300/193231465-4a8dadc0-da5a-4db3-8568-62ab82b47dd2.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/90816300/193231532-6ef1321b-bfb1-4131-944d-bc35c5649a5b.png)

**Note**
Please change the CSS of the Sign In page according to the Picture given, Don't change the Structure of the Page.

**Comment by sdeepanshu17** [comment]
Please assign this issue to me.

**Comment by Noothan-am** [comment]
hey @Jai-Solania-29 can i contribute to it ?

**Comment by Kanika637** [comment]
Since @sdeepanshu17  you have already been assigned an issue and also as per a first come first serve basis @Noothan-am  you are being assigned the issue✌️

**Comment by rockkidd23** [comment]
hi i can help in this issuee

**Comment by annupriy** [comment]
Please assign me this issue.

**Comment by Noothan-am** [comment]
hey @sdeepanshu17 i am not able to open it in browser ?

**Comment by Noothan-am** [comment]
> > hey @sdeepanshu17 i am not able to open it in browser.
> 
> Hey @Noothan-am , You can follow the steps in the Readme.md with which you can open it in your local browser. You can also use the Gitpod extension for this purpose. If you get stuck anywhere, just ping me!

ok

**Comment by Jai-Solania-29** [comment]
Any updates @Noothan-am ?

**Comment by Noothan-am** [comment]
> Any updates @Noothan-am ?

 @Jai-Solania-29 I am new to open-source i am unable to do it please assign it to someone else
thankyou
