### ISSUE TITLE
Change the Structure of the Shopping Cart Page

### ISSUE THREAD

**Issue by Jai-Solania-29** [Kanika637/amazon-clone#61]
Current behavior:

![Screenshot 2022-09-30 142655](https://user-images.githubusercontent.com/90816300/193234981-f73990ba-39b8-4893-8b17-0b6ffd105f69.png)

Expected behavior:

Something like this, Try to use your creativity 😃

![Screenshot 2022-09-30 143514](https://user-images.githubusercontent.com/90816300/193235239-81fd6451-12b9-4343-b89d-21762bc0e182.png)

**Comment by Jai-Solania-29** [comment]
Feel free to ping me or @Kanika637, If you have any doubt related to the issue.

**Comment by Souvik-Nayak** [comment]
Can i work on this issue @Jai-Solania-29. From the given snapshots i understood the alignment has to be done properly with "subtotal" printing at below !

**Comment by Kanika637** [comment]
Hey @Souvik-Nayak, Go ahead 🚀
