### ISSUE TITLE
Category Routes

### ISSUE THREAD

**Issue by Shivam-Katare** [Kanika637/amazon-clone#64]
Hi @Kanika637
I want to add "Shop By Category" products to the home section and would like to add routes for different categories. 
Please assign this issue to me.

**Comment by Kanika637** [comment]
hey @Shivam-Katare, could you please attach some screenshots of what you actually want to achieve🙌

**Comment by Shivam-Katare** [comment]
So, this is what I want to achieve. So, whenever the user clicks on this 👇 category image, it will redirect it to a new page that will contain the product of a similar category.

![Screenshot (65)](https://user-images.githubusercontent.com/91705825/193393196-4e773932-7333-48ae-a9a9-4160e2fb3a34.png)

**Comment by Kanika637** [comment]
Great @Shivam-Katare , Go ahead🚀
