### ISSUE TITLE
Automate build testing using github actions

### ISSUE THREAD

**Issue by harshit0571** [Kanika637/amazon-clone#74]
I think it would be great to add github actions to test pull requests.

**Comment by Kanika637** [comment]
Surely @harshit0571. We do need GitHub actions🙌

**Comment by harshit0571** [comment]
can you assign it to me please!!

**Comment by Kanika637** [comment]
Hey @harshit0571 , I am getting a error from the command ` docker-compose up -d --build`

![image](https://user-images.githubusercontent.com/84350895/193412972-6cb5e1c1-3324-4106-bc18-b7be075ff796.png)

**Comment by harshit0571** [comment]
It was working fine for me, let me check

**Comment by harshit0571** [comment]
![Screenshot from 2022-10-01 20-24-21](https://user-images.githubusercontent.com/62325935/193415346-2f0073dd-5bf2-4441-911b-70e4f337fcc1.png)

**Comment by harshit0571** [comment]
i think there is a problem with react-coursel-slider.

**Comment by harshit0571** [comment]
![Screenshot from 2022-10-01 21-00-34](https://user-images.githubusercontent.com/62325935/193416772-59c8d28c-a9d8-4d4d-a295-acf34347462b.png)

I tried removing react-coursel-slider package.

The problem is with **react-coursel-slider** package.
i think it is not working with the node version.

**Comment by harshit0571** [comment]
I think we should use something else to display coursel.

**Comment by Kanika637** [comment]
Ohh, will get back on this!

**Comment by harshit0571** [comment]
can i create github action file?

**Comment by harshit0571** [comment]
@Kanika637  please check my latest PR.
i have fixed the issue

**Comment by webcoderspeed** [comment]
Hello kanika, can I contribute to this issue.

**Comment by Kanika637** [comment]
Hey @webcoderspeed , Go ahead🚀
