### ISSUE TITLE
Enhancement: Make header responsive and some minor changes to header  

### ISSUE THREAD

**Issue by ShubhamPatil0723** [Kanika637/amazon-clone#79]
The header is not responsive, the position is sticky and the color is not similar to the amazon header

We can get these enhancements by adding media queries, picking colors, and removing the sticky position 

## Original Header 👇 
![amaon-header](https://user-images.githubusercontent.com/92074003/193449389-7ce9e6d7-18b6-4ad1-a1ac-a2e402f03673.jpg)

## Clone header 👇 
![amazon-clone-Header](https://user-images.githubusercontent.com/92074003/193449391-1b5717d8-0ff9-4380-a967-4aa884f2a0d7.jpg)

Can I work on this? @Kanika637

**Comment by Kanika637** [comment]
Go ahead @ShubhamPatil0723 🚀
And make sure all your code is updated, as we have recently merged a PR solving some parts of the header.

**Comment by ShubhamPatil0723** [comment]
Got it

**Comment by Jai-Solania-29** [comment]
Hey @ShubhamPatil0723, Go ahead with the mobile view responsiveness🚀

**Comment by ShubhamPatil0723** [comment]
Hey, I just saw the message that reverted my PR for this issue. Can I know the reason (I'm still a beginner so it would be beneficial for me to learn from mistakes if there where any) @Kanika637

**Comment by Kanika637** [comment]
Hey @ShubhamPatil0723, I had to revert the PR as you worked on the old design of the header. If you open it in your local environment then you will see that the header's design has been changed the search bar is smaller in size and other components has some spacing too. So you have to do the responsiveness on that header.

**Comment by ShubhamPatil0723** [comment]
> Hey @ShubhamPatil0723, I had to revert the PR as you worked on the old design of the header. If you open it in your local environment then you will see that the header's design has been changed the search bar is smaller in size and other components has some spacing too. So you have to do the responsiveness on that header.

No, It was an updated code but the width was dynamic based on the viewport since there are not many elements in that navBar it is taking up entire space but if we add more elements into it then it will scale down.
If you want I can add other elements that are present on the original nav bar, should I do that?

**Comment by ShubhamPatil0723** [comment]
> Hey @ShubhamPatil0723, I had to revert the PR as you worked on the old design of the header. If you open it in your local environment then you will see that the header's design has been changed the search bar is smaller in size and other components has some spacing too. So you have to do the responsiveness on that header.

No, It was an updated code but the width was dynamic based on the viewport since there are not many elements in that navBar it is taking up entire space but if we add more elements into it then it will scale down.
If you want I can add other elements that are present on the original nav bar, should I do that?

**Comment by ShubhamPatil0723** [comment]
Like this, Almost same design 
![amaon-header-comparision](https://user-images.githubusercontent.com/92074003/194719163-b79e3303-6b79-4d08-9aca-ef2db2da6835.jpg)

First one is original and second one(in blue theme) is clone
