### ISSUE TITLE
Enhancement: Make product card responsive

### ISSUE THREAD

**Issue by monciego** [Kanika637/amazon-clone#81]
Product cards in main section is not responsive and it overflows on mobile view.

Can enhance this by stacking cards on specific breakpoint

![image](https://user-images.githubusercontent.com/77731891/193525638-f5c4d80e-a8b0-477f-82cf-cb290930f496.png)

**Comment by bungambohlah** [comment]
Please assign this to me and I will solve it @Kanika637

**Comment by Kanika637** [comment]
Hey @monciego, Thanks for opening the issue. Go ahead🚀

> Please assign this to me and I will solve it @Kanika637 is that ok? @monciego

Hey, we have some more issues open, you can try them!
