### ISSUE TITLE
fix npm install error that comes in docker file

### ISSUE THREAD

**Issue by Kanika637** [Kanika637/amazon-clone#83]
**Describe the bug**

An error is coming while entering the command `docker-compose up -d --build`.

**Expected behaviour**

We want the website to run locally successfully after building the docker file with the command `docker-compose up -d --build`.

**Screenshots**

![image](https://user-images.githubusercontent.com/84350895/193624177-cf875f81-9cb3-40b7-b59e-7306dde84e56.png)

**Comment by aryan2909** [comment]
hey @Kanika637 pls assign me this issue

**Comment by Kanika637** [comment]
Hey @aryan2909 , Go ahead 🚀

**Comment by Kanika637** [comment]
Any updates @aryan2909 ?

**Comment by aklite** [comment]
hello @Kanika637 !!
have you tried adding to dockerfile to npm install 

"npm install --force"

**Comment by aklite** [comment]
I think this might work hit and trial 😅

**Comment by Kanika637** [comment]
Hey @aklite , I think the error has been resolved now!
