### ISSUE TITLE
improve the navbar

### ISSUE THREAD

**Issue by Kanika637** [Kanika637/amazon-clone#84]
**Current Behaviour**

![image](https://user-images.githubusercontent.com/84350895/193632051-9a4e49de-5e7c-4899-a3c9-c7ec3525b18b.png)

**Expected behaviour**

![image](https://user-images.githubusercontent.com/84350895/193631927-cc9e1603-968f-4b6e-86ca-9bb96ba37cbf.png)

**Additional context**
Increase the font size and try to achieve 100% similarity with the Expected Behaviour.

**Comment by Rounak-28** [comment]
@Kanika637 Can I work on this?

**Comment by Jai-Solania-29** [comment]
Hey, @Rounak-28 Thanks for showing interest 😃, but you have just made a PR on this project.
So let's just keep this issue for other newcomers 🚀
But if no one comes, then we are good to go 🎉

**Comment by Jai-Solania-29** [comment]
Also do add this hover effect to the Navbar, and make it render on the Shopping Cart page as well.

![image](https://user-images.githubusercontent.com/90816300/193638250-f3915979-f9ef-4b85-b4e7-724d47bb9421.png)

**Comment by trishitchar** [comment]
Hey!
Can I work with this issue?

**Comment by tokyo3001** [comment]
@Jai-Solania-29 Can you assign me this issue?

**Comment by Kanika637** [comment]
As per first come first serve basis, @trishitchar you are being assigned the issue🙌

**Comment by Kanika637** [comment]
@tokyo3001 you can find more issues to work on!🚀

**Comment by Aarav238** [comment]
Can i work on this issue? @Kanika637 @Jai-Solania-29

**Comment by hrsh22** [comment]
Hey @Kanika637 if no one is working on this issue, can you assign it to me?

**Comment by Kanika637** [comment]
@trishitchar Any updates? Otherwise, I will have to assign it to someone else.

**Comment by trishitchar** [comment]
@Kanika637 
Please unassigned me. 
I'm so sorry. I've made those navber but currently I'm outside from home. That's why I can't do it.
Will love to contribute in future 😁

**Comment by makdoom** [comment]
I would like to work on this issue, please assigned me ...!

**Comment by Kanika637** [comment]
Go ahead @makdoom 🚀

**Comment by hrsh22** [comment]
Hey @Kanika637 , according to first come, first serve, I should be assigned the issue😅

**Comment by Kanika637** [comment]
Hey @hrsh22 , Sorry for that, but you can find more issues to work on👀
