### ISSUE TITLE
Refactor repeated product component inside home component

### ISSUE THREAD

**Issue by monciego** [Kanika637/amazon-clone#86]
Refactor the repeated code inside the home component to follow the [dry principle](https://medium.com/0xcode/dry-dont-repeat-yourself-avoiding-redundancy-in-software-programming-e264ec97276e) in programming. This can be done by using the [map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) method. And much better if we separate the data and store to a json file.

**Comment by Kanika637** [comment]
Hey @monciego, Thanks for opening the issue🙌, but I think right now we don't actually require this enhancement.

**Comment by Kanika637** [comment]
Hey @monciego, Thanks for opening the issue🙌, but I think right now we don't actually require this enhancement.
