### ISSUE TITLE
[Frontend] - Major changes to Header 🛠

### ISSUE THREAD

**Issue by IAmTamal** [Kanika637/amazon-clone#94]
### Changes i'd recommend  :

 - The header has too big height and little bit of unorganized content
 - The seach bar can be larger (like in the original app)
 - The texts can be smaller for better UI/UX standards.
 - We can add `Cart` , `Return and Orders` options too

### Why to do these changes ? 

- Since it is  a clone, we get one step closer to original site
- A more premium look for the amazing website
- Better accessibility and UI/UX standards

### Describe the solution you'd like

This is what it should be looking like : 
![image](https://user-images.githubusercontent.com/72851613/194131410-a68b62e2-a9d2-450f-ba8e-77da6658dee1.png)

This is what it currently looks like : 
![image](https://user-images.githubusercontent.com/72851613/194131473-81ec54c0-5e3c-4d92-b2bc-bea4b9ecf3a5.png)

### Can i make it ? 

- If assigned, yes i will try my best to make it as similar as possible !

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by ShubhamPatil0723** [comment]
Hey, I am already working on this one in issue #79, If you are ok with it can you review my first changes? (I have added ss and gif)

**Comment by IAmTamal** [comment]
> Hey, I am already working on this one in issue #79, If you are ok with it can you review my first changes? (I have added ss and gif)

Shoots, i will close my issue. Thanks for letting me know !

**Comment by IAmTamal** [comment]
@ShubhamPatil0723 Make a PR - that way we all can review and talk about changes !
